'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/auth-context';
import { SidebarLayout } from '@/components/layout/sidebar-layout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export default function ReportsDashboardPage() {
  const router = useRouter();
  const { user, loading, isAuthenticated } = useAuth();

  const [recentReports] = useState([
    { id: '1', name: 'Monthly Claims Report', type: 'Operational', generatedDate: '2024-01-11T09:00:00', generatedBy: 'System', status: 'completed' },
    { id: '2', name: 'CMS PMB Report', type: 'Regulatory', generatedDate: '2024-01-10T14:30:00', generatedBy: 'Compliance Officer', status: 'completed' },
  ]);

  const [scheduledReports] = useState([
    { id: '1', name: 'Daily Claims Summary', frequency: 'Daily', nextRun: '2024-01-12T06:00:00', recipients: 'claims@day1main.co.za' },
    { id: '2', name: 'Weekly Financial Report', frequency: 'Weekly', nextRun: '2024-01-15T08:00:00', recipients: 'finance@day1main.co.za' },
  ]);

  useEffect(() => {
    if (!loading && !isAuthenticated) router.push('/login');
  }, [loading, isAuthenticated, router]);

  if (loading || !user) return <div className="min-h-screen flex items-center justify-center"><p>Loading...</p></div>;

  return (
    <SidebarLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Reporting Studio</h1>
          <p className="text-gray-600 mt-1">Generate and schedule reports</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="cursor-pointer hover:shadow-lg" onClick={() => router.push('/reports/regulatory')}>
            <CardHeader><CardTitle>Regulatory Reports</CardTitle></CardHeader>
            <CardContent>
              <p className="text-sm text-gray-600 mb-4">CMS, FSCA/PA, and SARS reports</p>
              <Button variant="outline" className="w-full">View Reports</Button>
            </CardContent>
          </Card>

          <Card className="cursor-pointer hover:shadow-lg" onClick={() => router.push('/reports/operational')}>
            <CardHeader><CardTitle>Operational Reports</CardTitle></CardHeader>
            <CardContent>
              <p className="text-sm text-gray-600 mb-4">Claims, financial, and member reports</p>
              <Button variant="outline" className="w-full">View Reports</Button>
            </CardContent>
          </Card>

          <Card className="cursor-pointer hover:shadow-lg" onClick={() => router.push('/reports/query-builder')}>
            <CardHeader><CardTitle>Ad-Hoc Queries</CardTitle></CardHeader>
            <CardContent>
              <p className="text-sm text-gray-600 mb-4">Build custom queries and exports</p>
              <Button variant="outline" className="w-full">Query Builder</Button>
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardHeader><CardTitle>Recent Reports</CardTitle></CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-3 px-4 font-medium">Report Name</th>
                    <th className="text-left py-3 px-4 font-medium">Type</th>
                    <th className="text-left py-3 px-4 font-medium">Generated</th>
                    <th className="text-left py-3 px-4 font-medium">Generated By</th>
                    <th className="text-left py-3 px-4 font-medium">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {recentReports.map((report) => (
                    <tr key={report.id} className="border-b hover:bg-gray-50">
                      <td className="py-3 px-4 font-medium">{report.name}</td>
                      <td className="py-3 px-4">{report.type}</td>
                      <td className="py-3 px-4">{new Date(report.generatedDate).toLocaleString()}</td>
                      <td className="py-3 px-4">{report.generatedBy}</td>
                      <td className="py-3 px-4">
                        <div className="flex gap-2">
                          <Button size="sm" variant="outline">Download</Button>
                          <Button size="sm" variant="outline">View</Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Scheduled Reports</CardTitle></CardHeader>
          <CardContent>
            <div className="space-y-3">
              {scheduledReports.map((report) => (
                <div key={report.id} className="flex items-center justify-between p-4 border rounded-lg">
                  <div className="flex-1">
                    <p className="font-medium">{report.name}</p>
                    <p className="text-sm text-gray-600">Frequency: {report.frequency}</p>
                    <p className="text-sm text-gray-600">Next run: {new Date(report.nextRun).toLocaleString()}</p>
                    <p className="text-xs text-gray-500">Recipients: {report.recipients}</p>
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" variant="outline">Edit</Button>
                    <Button size="sm" variant="outline">Run Now</Button>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </SidebarLayout>
  );
}
