import { ROLES } from './roles.constants'
import { PERMISSIONS } from './permissions.constants'

/**
 * Role-Permission Mappings
 * Defines which permissions each role has
 */
export const ROLE_PERMISSIONS_MAP: Record<string, string[]> = {
  // Member - basic access to own data
  [ROLES.MEMBER]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.CLAIM_SUBMIT,
    PERMISSIONS.PAYMENT_READ,
  ],

  // Employer Admin - manage group members
  [ROLES.EMPLOYER_ADMIN]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_WRITE,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.POLICY_WRITE,
    PERMISSIONS.PAYMENT_READ,
  ],

  // Broker - sales and commission access
  [ROLES.BROKER]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_WRITE,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.POLICY_WRITE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.BROKER_READ,
    PERMISSIONS.BROKER_COMMISSION,
    PERMISSIONS.MARKETING_READ,
  ],

  // Call Centre Agent - customer support
  [ROLES.CALL_CENTRE_AGENT]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.PAYMENT_READ,
  ],

  // Ambulance Operator - verify member status and benefits
  [ROLES.AMBULANCE_OPERATOR]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.BENEFIT_RULES_READ,
  ],

  // Claims Assessor - process claims (CANNOT change benefit rules)
  [ROLES.CLAIMS_ASSESSOR]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.CLAIM_ASSESS,
    PERMISSIONS.PROVIDER_READ,
    PERMISSIONS.BENEFIT_RULES_READ, // Can read but NOT write
  ],

  // Claims Supervisor - approve claims
  [ROLES.CLAIMS_SUPERVISOR]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.CLAIM_ASSESS,
    PERMISSIONS.CLAIM_APPROVE,
    PERMISSIONS.CLAIM_REJECT,
    PERMISSIONS.CLAIM_APPEAL,
    PERMISSIONS.PROVIDER_READ,
    PERMISSIONS.BENEFIT_RULES_READ,
  ],

  // Provider Admin - manage provider data
  [ROLES.PROVIDER_ADMIN]: [
    PERMISSIONS.PROVIDER_READ,
    PERMISSIONS.PROVIDER_WRITE,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.CLAIM_SUBMIT,
    PERMISSIONS.PAYMENT_READ,
  ],

  // Finance Clerk - process payments
  [ROLES.FINANCE_CLERK]: [
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
  ],

  // Finance Manager - approve payments and products
  [ROLES.FINANCE_MANAGER]: [
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.PAYMENT_APPROVE,
    PERMISSIONS.PAYMENT_REFUND,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.FINANCE_RECONCILE,
    PERMISSIONS.PRODUCT_APPROVE, // Required for product approval
  ],

  // Compliance Officer - approve products and manage compliance
  [ROLES.COMPLIANCE_OFFICER]: [
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.COMPLIANCE_WRITE,
    PERMISSIONS.COMPLIANCE_APPROVE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_APPROVE, // Required for product approval
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_KYC, // KYC/FICA compliance
  ],

  // Data Protection Officer - POPIA compliance
  [ROLES.DATA_PROTECTION_OFFICER]: [
    PERMISSIONS.POPIA_READ,
    PERMISSIONS.POPIA_WRITE,
    PERMISSIONS.POPIA_DSR_PROCESS,
    PERMISSIONS.POPIA_BREACH_MANAGE,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.MEMBER_READ,
  ],

  // Risk/Fraud Analyst - investigate fraud
  [ROLES.RISK_FRAUD_ANALYST]: [
    PERMISSIONS.FRAUD_READ,
    PERMISSIONS.FRAUD_INVESTIGATE,
    PERMISSIONS.FRAUD_RESOLVE,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_KYC, // KYC for risk assessment
    PERMISSIONS.PROVIDER_READ,
    PERMISSIONS.AUDIT_READ,
  ],

  // Product Manager - create products (cannot approve)
  [ROLES.PRODUCT_MANAGER]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_WRITE,
    PERMISSIONS.BENEFIT_RULES_READ,
    PERMISSIONS.BENEFIT_RULES_WRITE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.CLAIM_READ,
  ],

  // Actuary - pricing and risk analysis
  [ROLES.ACTUARY]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_WRITE,
    PERMISSIONS.BENEFIT_RULES_READ,
    PERMISSIONS.BENEFIT_RULES_WRITE,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
  ],

  // Operations Manager - daily business operations
  [ROLES.OPERATIONS_MANAGER]: [
    PERMISSIONS.OPERATIONS_READ,
    PERMISSIONS.OPERATIONS_WRITE,
    PERMISSIONS.OPERATIONS_DEBIT_ORDERS,
    PERMISSIONS.OPERATIONS_CALL_CENTRE,
    PERMISSIONS.OPERATIONS_ARREARS,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_WRITE,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.CLAIM_ASSESS,
    PERMISSIONS.PROVIDER_READ,
    PERMISSIONS.PROVIDER_WRITE,
    PERMISSIONS.BROKER_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
  ],

  // System Admin - full access
  [ROLES.SYSTEM_ADMIN]: [
    PERMISSIONS.SYSTEM_ADMIN,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_WRITE,
    PERMISSIONS.MEMBER_DELETE,
    PERMISSIONS.MEMBER_KYC,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.POLICY_WRITE,
    PERMISSIONS.POLICY_APPROVE,
    PERMISSIONS.POLICY_DELETE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_WRITE,
    PERMISSIONS.PRODUCT_APPROVE,
    PERMISSIONS.PRODUCT_PUBLISH,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.BENEFIT_RULES_READ,
    PERMISSIONS.BENEFIT_RULES_WRITE,
    PERMISSIONS.BENEFIT_RULES_APPROVE,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.CLAIM_SUBMIT,
    PERMISSIONS.CLAIM_ASSESS,
    PERMISSIONS.CLAIM_APPROVE,
    PERMISSIONS.CLAIM_REJECT,
    PERMISSIONS.CLAIM_APPEAL,
    PERMISSIONS.PROVIDER_READ,
    PERMISSIONS.PROVIDER_WRITE,
    PERMISSIONS.PROVIDER_APPROVE,
    PERMISSIONS.PROVIDER_DELETE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.PAYMENT_APPROVE,
    PERMISSIONS.PAYMENT_REFUND,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.FINANCE_RECONCILE,
    PERMISSIONS.BROKER_READ,
    PERMISSIONS.BROKER_WRITE,
    PERMISSIONS.BROKER_COMMISSION,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.COMPLIANCE_WRITE,
    PERMISSIONS.COMPLIANCE_APPROVE,
    PERMISSIONS.POPIA_READ,
    PERMISSIONS.POPIA_WRITE,
    PERMISSIONS.POPIA_DSR_PROCESS,
    PERMISSIONS.POPIA_BREACH_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.MARKETING_READ,
    PERMISSIONS.MARKETING_WRITE,
    PERMISSIONS.MARKETING_CAMPAIGN,
    PERMISSIONS.FRAUD_READ,
    PERMISSIONS.FRAUD_INVESTIGATE,
    PERMISSIONS.FRAUD_RESOLVE,
    PERMISSIONS.OPERATIONS_READ,
    PERMISSIONS.OPERATIONS_WRITE,
    PERMISSIONS.OPERATIONS_DEBIT_ORDERS,
    PERMISSIONS.OPERATIONS_CALL_CENTRE,
    PERMISSIONS.OPERATIONS_ARREARS,
  ],

  // Auditor - read-only access to everything
  [ROLES.AUDITOR]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.BENEFIT_RULES_READ,
    PERMISSIONS.CLAIM_READ,
    PERMISSIONS.PROVIDER_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.BROKER_READ,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.POPIA_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MARKETING_READ,
    PERMISSIONS.FRAUD_READ,
    PERMISSIONS.OPERATIONS_READ,
  ],
}

/**
 * Validate that Claims Assessor cannot change benefit rules
 * This enforces separation of duties requirement
 */
export function validateClaimsAssessorRestrictions(): boolean {
  const claimsAssessorPerms = ROLE_PERMISSIONS_MAP[ROLES.CLAIMS_ASSESSOR]
  
  // Claims Assessor should NOT have these permissions
  const forbiddenPermissions = [
    PERMISSIONS.BENEFIT_RULES_WRITE,
    PERMISSIONS.BENEFIT_RULES_APPROVE,
    PERMISSIONS.PRODUCT_WRITE,
    PERMISSIONS.PRODUCT_APPROVE,
  ]

  for (const forbidden of forbiddenPermissions) {
    if (claimsAssessorPerms.includes(forbidden)) {
      throw new Error(
        `RBAC Configuration Error: Claims Assessor should not have ${forbidden} permission`,
      )
    }
  }

  return true
}
